### ISSUE TITLE
Add support for previous Python version still maintained (3.4, 3.5)?

### ISSUE THREAD

**Issue by Delgan** [notifiers/notifiers#102]
Hi!

According to the [Status of Python branches](https://devguide.python.org/#status-of-python-branches), end-of-life for Python 3.4 and 3.5 are respectively scheduled for March 2019 and September 2020.

What are your thoughts on basing `notifiers` supported versions on the Python agenda?

I'm asking because I remember at first you were wondering if you should support Python 2.7 or not. Although maintaining both Python2.7 / Python3.+ is certainly a headache that is not worth it, adding support for 3.4 "just" requires to drop the use of f-strings. But it also implies not being able to enjoy these neat features before several years.

The advantage is to extend and facilitate the use, adding for example a "native" compatibility with Ubuntu 16.04 which is delivered with Python 3.5.

I do not have a pronounced opinion on the question, but I would like to know whether or not to consider `notifiers` as being Python3.6+ only.

**Comment by liiight** [comment]
I can't say I'm inclined to support previous version at this point. When I started this project I wanted to gain some experience with the latest version of python (which was 3.6.0 at the time). 

To my great delight, this project grew considerably since then, and it seems a lot of people use it.

So I'm open to making this change if there is a request for it. If 50 people upvote this issue, i'll implement this change.

**Comment by Delgan** [comment]
Yeah, it probably doesn't worth the trouble if too few people are planning to use `notifiers` with Python versions which are (soon to be) 2 major releases behind.

Thanks for the answer. 😉

**Comment by liiight** [comment]
Yeah, I don't see this happening anymore. Sorry
