### ISSUE TITLE
Notifiers may raise unexpected "KeyError"

### ISSUE THREAD

**Issue by Delgan** [notifiers/notifiers#104]
Hello.

Looking at this code sample for example, I would expect some `NotifierException` rather than a `KeyError`:

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import notifiers
>>> zulip = notifiers.providers.zulip.Zulip()
>>> zulip.notify(message="msg", email="me@gmail.com", api_key="abc", subject="test", to="you@gmail.com", domain="")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\delgan\AppData\Local\Programs\Python\Python36\lib\site-packages\notifiers\core.py", line 272, in notify
    data = self._process_data(**kwargs)
  File "C:\Users\delgan\AppData\Local\Programs\Python\Python36\lib\site-packages\notifiers\core.py", line 204, in _proces
s_data
    data = self._prepare_data(data)
  File "C:\Users\delgan\AppData\Local\Programs\Python\Python36\lib\site-packages\notifiers\providers\zulip.py", line 75,
in _prepare_data
    base_url = self.base_url.format(domain=data.pop('domain')) if data.get('domain') else data.pop('server')
KeyError: 'server'
```

The issue with using `if data.get(key)` is that it not only evaluates as `False` when the key is missing, but also when there is a "falsy" value.

I saw this recipe multiple time in the source code. Maybe `if key in data` should be used instead?

This is a minor detail (I am not even sure it deserves a fix?), but I'm reporting this in case it causes subtle bugs for providers accepting falsy values like `0`.

**Comment by liiight** [comment]
Thank you for reporting this!

You are right that the current way of checking is inadequate but I belive the optimal solution is to add a capability that's in my backlog for a while now, enforce formats via the schema. 

Since I currently heavily depend on the json schema for data validation, it makes sense to enforce format verifications on certain (if not most) fields, so sending an empty string for the "domain" value like your example, would be blocked on an earlier phase.

I'm currently pretty busy in my personal life but I'll make this addition the next priority as I was not aware the lack of it allows for issues such as this.

**Comment by Delgan** [comment]
Glad to hear that, thanks! 👍 

It's only an edge case, so there is nothing pressing.
